[project]
name = "agentic-rag-query-scheduler-poc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ritwikmath", email = "ritwikmath@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
agentic-rag-query-scheduler-poc = "agentic_rag_query_scheduler_poc:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"
